# Use postgres/example user/password credentials
version: '3.1'

services:

  pg:
    container_name: pg-instance
    image: proventa/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: user@domain.de
        PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    ports:
      - 80:80